jobs:
  build1:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - restore_cache:
	  name: Generate some file
          command |
              mkdir kaps
              echo "echo 'Hello Kapapa!! from a bash script'" > kaps/go.sum
	            chmod +x folder/go.sum
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: |
              go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports
  build2:
    working_directory: ~/repo
    docker:
      - image: circleci/php:7.3.12
    steps:
      - checkout
      - attach_workspace:
          at: tmp
      - run:
          name: use Artifact
          command: |
            ./tmp/kaps/go.sum
workflows:
  version: 2
  document:
      jobs:
        - build1
        - build2:
            requires:
                - build1